package itcr.model;

/**
 * InterruptMessage class represents a message generated by an interrupt.
 * It contains information about the core ID, interrupt code, message, and
 * process ID.
 */
public class InterruptMessage {
  private int coreId;
  private InterruptCode code;
  private String message;
  private int processId;

  /**
   * Constructor for InterruptMessage.
   *
   * @param coreId    the ID of the core that generated the interrupt
   * @param code      the interrupt code
   * @param message   the message associated with the interrupt
   * @param processId the ID of the process that generated the interrupt
   */
  public InterruptMessage(int coreId, InterruptCode code, String message, int processId) {
    this.coreId = coreId;
    this.code = code;
    this.message = message;
    this.processId = processId;
  }

  /**
   * Gets the ID of the core that generated the interrupt.
   *
   * @return the core ID
   */
  public int getCoreId() {
    return coreId;
  }

  /**
   * Gets the interrupt code.
   *
   * @return the interrupt code
   */
  public InterruptCode getCode() {
    return code;
  }

  /**
   * Gets the message associated with the interrupt.
   *
   * @return the message
   */
  public String getMessage() {
    return message;
  }

  /**
   * Gets the ID of the process that generated the interrupt.
   *
   * @return the process ID
   */
  public int getProcessId() {
    return processId;
  }

  /**
   * Returns a string representation of the interrupt message.
   *
   * @return a string representation of the interrupt message
   */
  @Override
  public String toString() {
    return "Core " + coreId + " - " + code + ": " + message;
  }
}